### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by landigf** [Bg735/AddressBook#18]

**Comment by landigf** [comment]
Perché manca il costruttore con i Tags ?

**Comment by landigf** [comment]
mi servirebbe toVCard e fromVCard da Contact, si può fare ?

Li uso nel FIleManager:

/**
     * Imports an AddressBook from a file.
     * 
     * @param path The file path of the VCard to be imported.
     * @return The AddressBook to be imported.
     * @throws StreamCorruptedException If the file stream is corrupted.
     */
    public static AddressBook importFromVCard(String path) throws StreamCorruptedException {
        AddressBook addressBook = new AddressBook();
        try (FileInputStream fis = new FileInputStream(path); VCardReader reader = new VCardReader(fis)) {
            VCard vCard;
            while ((vCard = reader.readNext()) != null) {
                addressBook.add(Contact.**fromVCard**(vCard));
            }
        } catch (IOException e) {
            throw new StreamCorruptedException("Failed to import from VCard: " + e.getMessage());
        }
        return addressBook;
    }

    /**
     * Exports an AddressBook to a VCard file.
     * 
     * @param path The file path to export the AddressBook as a VCard.
     * @param ab The AddressBook to be exported.
     * @throws StreamCorruptedException If the file stream is corrupted.
     */
    public static void exportAsVCard(String path, AddressBook ab) throws StreamCorruptedException, IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(path))) {
            VCardWriter vCardWriter = new VCardWriter(writer, VCardVersion.V3_0);
            
            // Iterate over AddressBook contacts and write them as VCards
            for (Contact contact : ab.contacts()) {
                // Write the vCard to the output stream
                vCardWriter.write(contact.**toVCard**());
            }
        // Close the writer automatically due to the try-with-resources
        }
    }

**Comment by Bg735** [comment]
Soddisfatte le richieste
